spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}/${DB_SCREEN_MATCH}
spring.datasource.username=${DB_USER_POSTGRES}
spring.datasource.password=${DB_PASSWORD_POSTGRES}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update